### ISSUE TITLE
Weird behavior while requesting data

### ISSUE THREAD

**Issue by tpalinski** [tpalinski/air-quality#23]
Requesting data for Gdynia Szafran for 1 - 2 jan 2021 yields unusual data for CO

**Comment by luluu9** [comment]
~~#27  fixes this issue. There was a typo both in the frontend and backend.~~ [commented bad issue]

**Comment by luluu9** [comment]
Looks like this station (PmGdySzafran) doesn't have data for CO. What should we be doing in this case?

**Comment by tpalinski** [comment]
We can't do much about it to be honest, i think leaving it as is is ok

**Comment by tpalinski** [comment]
Fixed by pr #33 - closing
